version: "3.8"

networks:
  local-dev:
    driver: bridge

volumes:
  postgres_data:

  rabbitmq_data:

  mongodb_data:

services:
  # keycloack:
  #   image: jboss/keycloak:${KEYCLOAK_VERSION}
  #   container_name: auth-provider
  #   networks:
  #     - local-dev

  #   volumes:
  #     - postgres_data:/opt/jboss/postgres_data

  #   environment:
  #     DB_VENDOR: postgres
  #     DB_ADDR: postgres
  #     DB_DATABASE: ${POSTGRESQL_DB}
  #     DB_USER: ${POSTGRESQL_USER}
  #     DB_PASSWORD: ${POSTGRESQL_PASS}

  # ports:
  #   - "28080:8080"
  # depends_on:
  #   - dev-postgres-db

  rabbitmq:
    image: rabbitmq:management

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  dev-postgres-db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  dev-mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"

  dev-mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_SERVER: dev-mongo-db
      ME_CONFIG_MONGODB_PORT: "27017"

    ports:
      - "8089:8081"

    depends_on:
      - dev-mongo-db
